### ISSUE TITLE
Version 14.0.1: Error with ESLint 8.57.0

### ISSUE THREAD

**Issue by elise-ng** [oursky/eslint-oursky#53]
```
Oops! Something went wrong! :(

ESLint: 8.57.0

Error: .eslintrc.js » plugin:@oursky/typescript:
	Configuration for rule "@typescript-eslint/no-unused-vars" is invalid:
	Value {"varsIgnorePattern":"^_","ignoreRestSiblings":true,"args":"all","argsIgnorePattern":"^_","caughtErrors":"all","caughtErrorsIgnorePattern":"^_","destructuredArrayIgnorePattern":"^_"} should be equal to one of the allowed values.
	Value {"varsIgnorePattern":"^_","ignoreRestSiblings":true,"args":"all","argsIgnorePattern":"^_","caughtErrors":"all","caughtErrorsIgnorePattern":"^_","destructuredArrayIgnorePattern":"^_"} should NOT have additional properties.
	Value {"varsIgnorePattern":"^_","ignoreRestSiblings":true,"args":"all","argsIgnorePattern":"^_","caughtErrors":"all","caughtErrorsIgnorePattern":"^_","destructuredArrayIgnorePattern":"^_"} should match exactly one schema in oneOf.

    at ConfigValidator.validateRuleOptions (/Users/elise/Development/_Oursky/clover-crm/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2048:23)
    at /Users/elise/Development/_Oursky/clover-crm/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2103:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/Users/elise/Development/_Oursky/clover-crm/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2100:34)
    at ConfigValidator.validateConfigArray (/Users/elise/Development/_Oursky/clover-crm/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2226:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/elise/Development/_Oursky/clover-crm/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3985:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/elise/Development/_Oursky/clover-crm/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3791:21)
    at FileEnumerator._iterateFilesRecursive (/Users/elise/Development/_Oursky/clover-crm/node_modules/eslint/lib/cli-engine/file-enumerator.js:450:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/elise/Development/_Oursky/clover-crm/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:49)
```

**Comment by elise-ng** [comment]
ping @louischan-oursky

**Comment by elise-ng** [comment]
seems to be this rule causing the issue: https://github.com/oursky/eslint-oursky/blob/eaff48d9a044200258b6a03b29f3d3b434410853/src/configs/typescript.mjs#L157

**Comment by louischan-oursky** [comment]
What is your resolved version of `@typescript-eslint`?

**Comment by louischan-oursky** [comment]
I added this https://github.com/oursky/eslint-oursky/commit/06771b0c61095a140c0d764654cc46bce7e395be
and the test passed https://github.com/oursky/eslint-oursky/actions/runs/10767716165/job/29855532605

**Comment by louischan-oursky** [comment]
This issue is no longer relevant to 15.0.0, which supports eslint 9 and flat config.
